3 course/aspnet_labs/lab3/Lab3/Controllers/ToDoListController.cs
using Lab3.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Lab3.Controllers
{
    public class ToDoListController : Controller
    {
        private readonly ILogger<ToDoListController> _logger;
        private ToDoListRepository _repository;
        public ToDoListController(ILogger<ToDoListController> logger, ToDoListRepository repository)
        {
            _logger = logger;
            _repository = repository;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _repository.List());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(ToDoListModel toDoList)
        {
            await _repository.Add(toDoList);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> Update(Int64 Id)
        {
            return View(await _repository.GetItemById(Id));
        }
        [HttpPost]
        public async Task<IActionResult> Update(ToDoListModel toDoList)
        {
            await _repository.Update(toDoList);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> Delete(Int64 Id)
        {
            await _repository.Remove(Id);
            return RedirectToAction("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

3 course/aspnet_labs/lab3/Lab3/Controllers/ToDoListItemController.cs
using Lab3.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Lab3.Controllers
{
    public class ToDoListItemController : Controller
    {
        private readonly ILogger<ToDoListItemController> _logger;
        private ToDoListItemRepository _repository;
        private ToDoListRepository _listRepository;
        public ToDoListItemController(ILogger<ToDoListItemController> logger, ToDoListItemRepository repository, ToDoListRepository listRepository)
        {
            _logger = logger;
            _repository = repository;
            _listRepository = listRepository;
        }
        public async Task<IActionResult> Index(Int64 Id)
        {
            ViewBag.ListId = Id;
            ViewBag.ListName = (await _listRepository.GetItemById(Id)).Name;
            return View(await _repository.List(Id));
        }
        [HttpGet]
        public async Task<IActionResult> Create(Int64 Id)
        {
            ViewBag.ListId = Id;
            ViewBag.ListName = (await _listRepository.GetItemById(Id)).Name;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(ToDoListItemModel toDoListItem)
        {
            await _repository.Add(toDoListItem);
            return RedirectToAction("Index", new { Id = toDoListItem.ListId });
        }
        [HttpGet]
        public async Task<IActionResult> Update(Int64 Id)
        {
            var updatingItem = await _repository.GetItemById(Id);
            ViewBag.ListName = (await _listRepository.GetItemById(updatingItem.ListId)).Name;
            return View(await _repository.GetItemById(Id));
        }
        [HttpPost]
        public async Task<IActionResult> Update(ToDoListItemModel toDoListItem)
        {
            await _repository.Update(toDoListItem);
            return RedirectToAction("Index", new { Id = toDoListItem.ListId });
        }
        [HttpPost]
        public async Task<IActionResult> Delete(Int64 Id)
        {
            await _repository.Remove(Id);
            return Redirect(Request.Headers["Referer"].ToString());
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

3 course/aspnet_labs/lab3/Lab3/Views/ToDoListItem/Create.cshtml
@{
    ViewData["Title"] = "Добавление нового дела в список - " + @ViewBag.ListName;
}

<div class="text-center">
    <h1 class="display-4">Добавление нового дела в список - @ViewBag.ListName</h1>
    <form method="post" class="text-left">
        <input type="text" name="ListId" id="ListId" value="@ViewBag.ListId" hidden>
        <p>
            <label for="Name"><b>Название:</b></label><br>
            <input type="text" name="Name" id="Name" class="w-100" required>
        </p>
        <p>
            <label for="Done"><b>Выполнено?:</b></label><br>
            <input type="checkbox" name="Done" id="Done" value="true">
        </p>
        <input type="submit" value="Добавить">
    </form>
</div>

3 course/aspnet_labs/lab3/Lab3/Views/ToDoListItem/Index.cshtml
@model IEnumerable<Lab3.Models.ToDoListItemModel>
@{
    ViewData["Title"] = "Дела в списке - " + @ViewBag.ListName;
}

<div class="text-center">
    <h1 class="display-4">Дела в списке - @ViewBag.ListName</h1>
    <form method="post">
            <table class="table table-hover">
                <thead>
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Название дела</th>
                    <th scope="col">Выполнено?</th>
                    <th scoep="col">Действия</th>
                </tr>
            </thead>
            <tbody>
                @{
                    int i = 1;
                }
                @foreach (var item in Model)
                {
                        <tr>
                            <th scope="row">@(i++)</th>
                            <td class="w-100">@item.Name</td>
                            <td>@item.Done</td>
                            <td nowrap>
                                <a class="btn btn-outline-primary" asp-controller="ToDoListItem" asp-action="Update"
                            asp-route-id="@item.ItemId">Изменить</a> |
                                <input class="btn btn-danger" type="submit" value="X" asp-controller="ToDoListItem"
                            asp-action="Delete" asp-route-id="@item.ItemId">
                            </td>
                        </tr>
                }
            </tbody>
        </table>
    </form>
    <a class="btn btn-outline-primary" asp-controller="ToDoListItem" asp-action="Create" asp-route-id="@ViewBag.ListId">Добавить новое дело</a>
    <a class="btn btn-danger" asp-controller="ToDoList" asp-action="Index">Вернуться</a>
</div>

3 course/aspnet_labs/lab3/Lab3/Views/ToDoListItem/Update.cshtml
@model Lab3.Models.ToDoListItemModel
@{
    ViewData["Title"] = "Редактирование дела в списке - " + @ViewBag.ListName;
}

<div class="text-center">
    <h1 class="display-4">Редактирование дела в списке - @ViewBag.ListName</h1>
    <form method="post" class="text-left">
        <input type="text" name="ItemId" id="ItemId" value="@Model.ItemId" hidden>
        <input type="text" name="ListId" id="ListId" value="@Model.ListId" hidden>
        <p>
            <label for="Name"><b>Название:</b></label><br>
            <input type="text" name="Name" id="Name" value="@Model.Name" class="w-100" required>
        </p>
        <p>
            <label for="Done"><b>Выполнено?:</b></label><br>
            <input type="checkbox" name="Done" id="Done" value="true" checked="@Model.Done">
        </p>
        <input type="submit" value="Сохранить изменения">
    </form>
</div>