3 course/aspnet_labs/lab2/Lab2/Pages/Create.cshtml.cs
using System;
using Lab2.Data;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc;

namespace Lab2.Pages
{
    public class CreateModel : PageModel
    {
        private ToDoListRepositary repositary;
        public CreateModel(ToDoListRepositary repositary)
        {
            this.repositary = repositary;
        }
        public void OnGet()
        {

        }
        public IActionResult OnPost(string name, bool done, Int16 priority)
        {
            repositary.Add(new ToDoListItem(name, done, priority));
            return RedirectToPage("Index");
        }
    }
}

3 course/aspnet_labs/lab2/Lab2/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System.Diagnostics;

namespace Lab2.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

3 course/aspnet_labs/lab2/Lab2/Pages/Index.cshtml.cs
using System;
using Lab2.Data;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc;

namespace Lab2.Pages
{
    public class IndexModel : PageModel
    {
        public ToDoListRepositary repositary;
        public IndexModel(ToDoListRepositary repositary)
        {
            this.repositary = repositary;
        }

        public void OnGet()
        {

        }
        public IActionResult OnPostRemove(Guid id)
        {
            repositary.Remove(id);
            return RedirectToPage();
        }
    }
}

3 course/aspnet_labs/lab2/Lab2/Pages/Update.cshtml.cs
using System;
using Lab2.Data;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace Lab2.Pages
{
    public class UpdateModel : PageModel
    {
        private ToDoListRepositary repositary;
        public ToDoListItem updatingItem;
        public UpdateModel(ToDoListRepositary repositary)
        {
            this.repositary = repositary;
        }
        public void OnGet(Guid Id)
        {
            updatingItem = repositary.GetItemById(Id);
        }
        public IActionResult OnPost(Guid Id, string name, bool done, Int16 priority)
        {
            repositary.Update(new ToDoListItem(Id, name, done, priority));
            return RedirectToPage("Index");
        }
    }
}

3 course/aspnet_labs/lab2/Lab2/Pages/Create.cshtml
@page
@model CreateModel
@{
    ViewData["Title"] = "Добавление дела в список";
}

<div class="text-center">
    <h1 class="display-4">Добавление дела в список</h1>
    <form method="post" class="text-left">
        <p>
            <label for="name"><b>Тема:</b></label><br>
            <input type="text" name="name" id="name" class="w-100" required>
        </p>
        <p>
            <label for="done"><b>Выполнено?</b></label>
            <input type="checkbox" name="done" id="done" value="true">
        </p>
        <p>
            <label for="priority"><b>Приоритет:</b></label><br>
            <input type="number" name="priority" id="priority" value="0">
        </p>
        <input type="submit" value="Добавить">
    </form>
</div>

3 course/aspnet_labs/lab2/Lab2/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Список дел";
}

<div class="text-center">
    <h1 class="display-4">Список дел</h1>
    <form method="post">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Тема</th>
                    <th scope="col">Выполнено?</th>
                    <th scope="col">Приоритет</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @{
                    int i = 1;
                }
                @foreach (var item in Model.repositary.List())
                {
                    <tr>
                        <th scope="row">@(i++)</th>
                        <td>@item.name</td>
                        <td>@item.done</td>
                        <td>@item.priority</td>
                        <td>
                            <a class="btn btn-outline-primary" asp-page="Update" asp-route-id="@item.Id">Изменить</a> |
                            <input class="btn btn-danger" type="submit" value="X" asp-page-handler="remove"
                                asp-route-id="@item.Id">
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </form>
    <a asp-page="Create" class="btn btn-outline-primary">Добавить новое дело</a>
</div>

3 course/aspnet_labs/lab2/Lab2/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lab2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Lab2</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Lab2 - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

3 course/aspnet_labs/lab2/Lab2/Pages/Update.cshtml
@page
@model UpdateModel
@{
    ViewData["Title"] = "Редактирование дела в списке";
}

<div class="text-center">
    <h1 class="display-4">Редактирование дела в списке</h1>
    <form method="post" class="text-left">
        <p>
            <label for="name"><b>Тема:</b></label><br>
            <input type="text" name="name" id="name" value="@Model.updatingItem.name" class="w-100" required>
        </p>
        <p>
            <label for="done"><b>Выполнено?</b></label>
            <input type="checkbox" name="done" id="done" value="true" checked="@Model.updatingItem.done">
        </p>
        <p>
            <label for="priority"><b>Приоритет:</b></label><br>
            <input type="number" name="priority" id="priority" value="@Model.updatingItem.priority">
        </p>
        <input type="submit" value="Сохранить изменения">
    </form>
</div>